version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: "python project/manage.py runserver"
    tty: true
    ports:
      - "8000:8000"
