---
- hosts: all
  roles:
    - role: ansible-docker-deployment
      vars:
        docker_deployment_project_name: gamification-api
        docker_deployment_release_name: '{{ build_number }}'
        docker_deployment_release_files:
          - local: ../docker-compose.run.yml
            remote: docker-compose.yml
          - local: ../.env
            remote: .env
        docker_deployment_shared_files:
          - local: ./shared/db.sqlite3
            remote: db.sqlite3
        docker_deployment_aws_ecr_repository: 755952719952.dkr.ecr.eu-west-1.amazonaws.com
