# Generated by Django 2.2.5 on 2019-09-04 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='QuestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('place', models.TextField()),
                ('instructions', models.TextField()),
                ('value_points', models.IntegerField(null=True)),
                ('beacon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Beacon')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quest', to='main.Quest')),
            ],
        ),
    ]
