# Generated by Django 2.2.5 on 2019-09-04 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_extendeduser_quest_queststep'),
    ]

    operations = [
        migrations.AddField(
            model_name='queststep',
            name='quest_index',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extendeduser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
