# Generated by Django 2.2.5 on 2019-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_quest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='epilogue',
            field=models.TextField(blank=True),
        ),
    ]
