# Generated by Django 2.2.5 on 2019-11-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quest_epilogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
