# Generated by Django 2.2.5 on 2019-11-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quest_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='queststep',
            name='value_points_error',
            field=models.IntegerField(null=True),
        ),
    ]
