# Generated by Django 2.2.5 on 2019-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_queststep_value_points_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.FileField(blank=True, upload_to='quests'),
        ),
    ]
