# Generated by Django 2.2.5 on 2019-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='queststep',
            name='image',
            field=models.FileField(blank=True, upload_to='quests_steps'),
        ),
    ]
