# Generated by Django 2.2.5 on 2019-11-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_queststep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_index',
            field=models.IntegerField(null=True),
        ),
    ]
