name: CI beacon-gamification-backend

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose --ansi never build --pull
    - name: Run the Docker image
      run: docker-compose --ansi never run --rm --no-deps app python --version
